CREATE DATABASE quickship;
USE quickship;

-- customers table

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(50),
    city VARCHAR(30),
    signup_date DATE
);

INSERT INTO customers VALUES
(1,'Rohan','Mumbai','2024-01-10'),
(2,'Priya','Pune','2024-02-15'),
(3,'Amit','Nagpur','2024-03-12'),
(4,'Sneha','Delhi','2024-01-22'),
(5,'Vikas','Mumbai','2024-04-05'),
(6,'Ananya','Pune','2024-05-10'),
(7,'Kunal','Nagpur','2024-06-18'),
(8,'Meera','Delhi','2024-07-20'),
(9,'Arjun','Mumbai','2024-08-11'),
(10,'Neha','Pune','2024-09-05');

SELECT * FROM customers;

-- drivers table

CREATE TABLE drivers (
    driver_id INT PRIMARY KEY,
    driver_name VARCHAR(50),
    city VARCHAR(30),
    joining_date DATE
);

INSERT INTO drivers VALUES
(101,'Rahul','Mumbai','2023-01-10'),
(102,'Suresh','Pune','2023-03-15'),
(103,'Karan','Nagpur','2023-05-20'),
(104,'Anil','Delhi','2023-08-01'),
(105,'Vivek','Mumbai','2024-01-01'),
(106,'Manoj','Pune','2024-02-01');

SELECT * FROM drivers;

-- warehouses table

CREATE TABLE warehouses (
    warehouse_id INT PRIMARY KEY,
    warehouse_name VARCHAR(50),
    city VARCHAR(30)
);

INSERT INTO warehouses VALUES
(1,'WH-Mumbai','Mumbai'),
(2,'WH-Pune','Pune'),
(3,'WH-Nagpur','Nagpur'),
(4,'WH-Delhi','Delhi');

SELECT * FROM warehouses;

-- orders table

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    warehouse_id INT,
    order_date DATE,
    order_value DECIMAL(10,2),
    FOREIGN KEY(customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY(warehouse_id) REFERENCES warehouses(warehouse_id)
);

INSERT INTO orders VALUES
(1001,1,1,'2025-01-05',5000),
(1002,2,2,'2025-01-08',3000),
(1003,3,3,'2025-01-10',4500),
(1004,1,1,'2025-02-01',7000),
(1005,4,4,'2025-02-04',6500),
(1006,5,1,'2025-02-15',2000),
(1007,2,2,'2025-03-01',8000),
(1008,3,3,'2025-03-05',5500),
(1009,6,2,'2025-03-10',3500),
(1010,7,3,'2025-03-15',6200),
(1011,8,4,'2025-04-01',7500),
(1012,9,1,'2025-04-03',4200),
(1013,10,2,'2025-04-05',9000),
(1014,1,1,'2025-04-10',3000),
(1015,2,2,'2025-04-15',6500),
(1016,3,3,'2025-05-01',7000),
(1017,4,4,'2025-05-02',5500),
(1018,5,1,'2025-05-05',4000),
(1019,6,2,'2025-05-08',2500),
(1020,7,3,'2025-05-10',10000);

SELECT * FROM orders;

-- deliveries table

CREATE TABLE deliveries (
    delivery_id INT PRIMARY KEY,
    order_id INT,
    driver_id INT,
    delivery_date DATE,
    delivery_time_hours INT,
    status VARCHAR(20),
    FOREIGN KEY(order_id) REFERENCES orders(order_id),
    FOREIGN KEY(driver_id) REFERENCES drivers(driver_id)
);

INSERT INTO deliveries VALUES
(1,1001,101,'2025-01-06',5,'Delivered'),
(2,1002,102,'2025-01-09',8,'Delivered'),
(3,1003,103,'2025-01-11',12,'Delivered'),
(4,1004,101,'2025-02-02',4,'Delivered'),
(5,1005,104,'2025-02-05',15,'Delayed'),
(6,1006,105,'2025-02-16',6,'Delivered'),
(7,1007,102,'2025-03-02',20,'Delayed'),
(8,1008,103,'2025-03-06',7,'Delivered'),
(9,1009,106,'2025-03-11',5,'Delivered'),
(10,1010,103,'2025-03-16',11,'Delivered'),
(11,1011,104,'2025-04-02',18,'Delayed'),
(12,1012,101,'2025-04-04',6,'Delivered'),
(13,1013,102,'2025-04-06',9,'Delivered'),
(14,1014,105,'2025-04-11',5,'Delivered'),
(15,1015,106,'2025-04-16',14,'Delayed'),
(16,1016,103,'2025-05-02',7,'Delivered'),
(17,1017,104,'2025-05-03',16,'Delayed'),
(18,1018,101,'2025-05-06',5,'Delivered'),
(19,1019,106,'2025-05-09',6,'Delivered'),
(20,1020,103,'2025-05-11',10,'Delivered');

SELECT * FROM deliveries;

# indexes

CREATE INDEX idx_cust_city
ON customers(city);

CREATE INDEX idx_order_date
ON orders(order_date);

CREATE INDEX idx_order_cust
ON orders(customer_id);

CREATE INDEX idx_delivery_status
ON deliveries(status);

CREATE INDEX idx_driver_city
ON drivers(city);


## Q1. Find all customers who registered in 2024.

SELECT customer_name
FROM customers 
WHERE signup_date LIKE '2024%';

## Q2. Display all orders whose value exceeds 5000.

SELECT *
FROM orders
WHERE order_value > 5000;

## Q3. Find drivers working in Mumbai.

SELECT driver_name
FROM drivers
WHERE city = "Mumbai";

## Q4. Count total orders placed.

SELECT COUNT(*) AS total_count
FROM orders;

## Q5. Find average order value.

SELECT AVG(order_value) AS order_value
FROM orders;

## Q6. Show customer names along with their orders.

SELECT c.customer_name AS cust_name, o.order_id AS order_id, o.order_date AS order_date, o.order_value AS order_value
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
ORDER BY order_id ASC;

## Q7. Find total revenue generated by each city.

DESCRIBE orders;
DESCRIBE customers;

SELECT c.city AS city, SUM(o.order_value) AS order_value
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.city;

## Q8. Find drivers who delivered more than one order.

DESCRIBE drivers;
DESCRIBE deliveries;

SELECT d1.driver_id AS driver_id, d1.driver_name AS driver_name, COUNT(d2.delivery_id) AS total_deliveries
FROM drivers d1
LEFT JOIN deliveries d2
ON d1.driver_id = d2.driver_id
GROUP BY d1.driver_id, d1.driver_name
HAVING COUNT(*) > 1
ORDER BY total_deliveries ASC;

## Q9. Find warehouses that processed orders worth more than Rs.10000.

DESCRIBE warehouses;
DESCRIBE orders;

SELECT w.warehouse_id AS warehouse_id, w.warehouse_name AS warehouse_name, SUM(o.order_value) as order_value
FROM warehouses w
JOIN orders o
ON w.warehouse_id = o.warehouse_id
GROUP BY warehouse_id, warehouse_name
HAVING SUM(o.order_value) > 10000;

## Q10. Show top 3 customers by total spending.

DESCRIBE customers;

SELECT c.customer_name AS customer_name, SUM(o.order_value) AS order_value
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY customer_name
ORDER BY order_value DESC
LIMIT 3;

## Q11. Find customers who placed orders in at least two different months.

DESCRIBE customers;
DESCRIBE orders;

SELECT c.customer_id AS customer_id, c.customer_name AS customer_name
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT DATE_FORMAT(order_date, '%y-%m')) >= 2;


## Q12. Find the driver with the lowest average delivery time.

DESCRIBE drivers;
DESCRIBE deliveries;

SELECT d1.driver_id AS driver_id, d1.driver_name AS driver_name, AVG(d2.delivery_time_hours) AS lowest_avg_delivery_time
FROM drivers d1
JOIN deliveries d2
ON d1.driver_id = d2.driver_id
GROUP BY d1.driver_id, d1.driver_name
ORDER BY lowest_avg_delivery_time ASC
LIMIT 1;

-- OR

-- (using subqueries)

SELECT *
FROM (SELECT
		d1.driver_id AS driver_id,
		d1.driver_name AS driver_name,
		AVG(d2.delivery_time_hours) AS lowest_avg_delivery_time
	FROM drivers d1
    JOIN deliveries d2
    ON d1.driver_id = d2.driver_id
    GROUP BY driver_id, driver_name
) AS t
WHERE lowest_avg_delivery_time = (
SELECT MIN(avg_time)
FROM (
SELECT
	AVG(delivery_time_hours) AS avg_time
	FROM deliveries 
	GROUP BY driver_id
) AS x
);

## Q14. Find the month with the highest revenue.

DESCRIBE orders;

# normal way

SELECT DATE_FORMAT(order_date,'%m') AS month, SUM(order_value) AS highest_revenue
FROM orders
GROUP BY month
ORDER BY highest_revenue DESC
LIMIT 1;

# using subquery

SELECT *
FROM 
( SELECT 	
		DATE_FORMAT(order_date,'%m') AS month,
		SUM(order_value) AS max_revenue
        FROM orders
        GROUP BY DATE_FORMAT(order_date,'%m')
        ORDER BY max_revenue DESC
        LIMIT 1
) t 
WHERE max_revenue = (
SELECT
	MAX(max_revenue)
FROM 
	(SELECT
			SUM(order_value) AS max_revenue
            FROM orders
            GROUP BY DATE_FORMAT(order_date,'%m')
) x
) ;

## Q15. Identify customers whose spending is above the overall average customer spending.

SELECT c.customer_id, c.customer_name, SUM(o.order_value) AS max_avg
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING SUM(o.order_value) > (SELECT AVG(total_spending) FROM 
( SELECT 
	customer_id,
	SUM(order_value) AS total_spending
    FROM orders
    GROUP BY customer_id
) t
);

SELECT * FROM orders;

## Q17. Find drivers responsible for delayed deliveries and count delays.

DESCRIBE drivers;
DESCRIBE deliveries;

SELECT d1.driver_id AS driver_id, d1.driver_Name AS driver_name, COUNT(d2.status) AS delay_counts
FROM drivers d1
JOIN deliveries d2
ON d1.driver_id = d2.driver_id
WHERE d2.status = "Delayed"
GROUP BY d1.driver_id, d1.driver_name
ORDER BY driver_id ASC;

## Q18. Find warehouses where average delivery time exceeds company average.

DESCRIBE warehouses;
DESCRIBE deliveries;
DESCRIBE orders;

SELECT w.warehouse_id AS warehoue_id, w.warehouse_name AS warehouse_name, AVG(d.delivery_time_hours) AS avg_delivery_time
FROM warehouses w
JOIN orders o
ON w.warehouse_id = o.warehouse_id
JOIN deliveries d
ON o.order_id = d.order_id
GROUP BY w.warehouse_id, w.warehouse_name
HAVING AVG(d.delivery_time_hours) > (
	SELECT AVG(delivery_time_hours)
    FROM deliveries
);

## Q19. Detect customers who have not placed any order in the last 30 days from their most recent order.

SELECT * FROM orders;

SELECT c.customer_id AS customer_id, c.customer_name AS customer_name,MAX(o.order_date) AS last_order_date
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING DATEDIFF((SELECT MAX(order_date) FROM orders),MAX(o.order_date)) > 30
ORDER BY customer_id ASC;